--------------------------------------------------------
--  File created - пятница-марта-13-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEPARTMENTS_EMPLOYEES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##KSENIA"."DEPARTMENTS_EMPLOYEES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEPARTMENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##KSENIA"."DEPARTMENTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##KSENIA"."EMPLOYEES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROJECTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "C##KSENIA"."PROJECTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "C##KSENIA"."DEPARTMENTS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENTS_EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "C##KSENIA"."DEPARTMENTS_EMPLOYEES" 
   (	"ID" NUMBER(*,0), 
	"DEPARTMENT_ID" NUMBER(*,0), 
	"EMPLOYEE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "C##KSENIA"."EMPLOYEES" 
   (	"ID" NUMBER(*,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"PATHER_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"POSITION" VARCHAR2(50 BYTE), 
	"SALARY" NUMBER(18,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROJECTS
--------------------------------------------------------

  CREATE TABLE "C##KSENIA"."PROJECTS" 
   (	"ID" NUMBER(*,0), 
	"NAME" VARCHAR2(200 BYTE), 
	"COST" NUMBER(18,2), 
	"DEPARTMENT_ID" NUMBER(*,0), 
	"DATE_BEG" DATE, 
	"DATE_END" DATE, 
	"DATE_END_REAL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into C##KSENIA.DEPARTMENTS
SET DEFINE OFF;
REM INSERTING into C##KSENIA.DEPARTMENTS_EMPLOYEES
SET DEFINE OFF;
REM INSERTING into C##KSENIA.EMPLOYEES
SET DEFINE OFF;
REM INSERTING into C##KSENIA.PROJECTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index DEPARTMENTS_EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##KSENIA"."DEPARTMENTS_EMPLOYEES_PK" ON "C##KSENIA"."DEPARTMENTS_EMPLOYEES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DEPARTMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##KSENIA"."DEPARTMENTS_PK" ON "C##KSENIA"."DEPARTMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##KSENIA"."EMPLOYEES_PK" ON "C##KSENIA"."EMPLOYEES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROJECTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##KSENIA"."PROJECTS_PK" ON "C##KSENIA"."PROJECTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger DEPARTMENTS_EMPLOYEES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "C##KSENIA"."DEPARTMENTS_EMPLOYEES_TRG" 
BEFORE INSERT ON DEPARTMENTS_EMPLOYEES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DEPARTMENTS_EMPLOYEES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##KSENIA"."DEPARTMENTS_EMPLOYEES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEPARTMENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "C##KSENIA"."DEPARTMENTS_TRG" 
BEFORE INSERT ON DEPARTMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT DEPARTMENTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##KSENIA"."DEPARTMENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "C##KSENIA"."EMPLOYEES_TRG" 
BEFORE INSERT ON EMPLOYEES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EMPLOYEES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##KSENIA"."EMPLOYEES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROJECTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "C##KSENIA"."PROJECTS_TRG" 
BEFORE INSERT ON PROJECTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PROJECTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C##KSENIA"."PROJECTS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "C##KSENIA"."DEPARTMENTS" ADD CONSTRAINT "DEPARTMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##KSENIA"."DEPARTMENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."DEPARTMENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENTS_EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "C##KSENIA"."DEPARTMENTS_EMPLOYEES" ADD CONSTRAINT "DEPARTMENTS_EMPLOYEES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##KSENIA"."DEPARTMENTS_EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."DEPARTMENTS_EMPLOYEES" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."DEPARTMENTS_EMPLOYEES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "C##KSENIA"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##KSENIA"."EMPLOYEES" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."EMPLOYEES" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."EMPLOYEES" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."EMPLOYEES" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."EMPLOYEES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECTS
--------------------------------------------------------

  ALTER TABLE "C##KSENIA"."PROJECTS" ADD CONSTRAINT "PROJECTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "C##KSENIA"."PROJECTS" MODIFY ("DATE_END" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."PROJECTS" MODIFY ("DATE_BEG" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."PROJECTS" MODIFY ("DEPARTMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."PROJECTS" MODIFY ("COST" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."PROJECTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##KSENIA"."PROJECTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DEPARTMENTS_EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "C##KSENIA"."DEPARTMENTS_EMPLOYEES" ADD CONSTRAINT "FK_DEPS_EMPLOYEES_DEPTS" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "C##KSENIA"."DEPARTMENTS" ("ID") ENABLE;
  ALTER TABLE "C##KSENIA"."DEPARTMENTS_EMPLOYEES" ADD CONSTRAINT "FK_DEPTS_EMPLOYEES_EMPLOYEES" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "C##KSENIA"."EMPLOYEES" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROJECTS
--------------------------------------------------------

  ALTER TABLE "C##KSENIA"."PROJECTS" ADD CONSTRAINT "FK_PROJECTS_DEPARTMENTS" FOREIGN KEY ("DEPARTMENT_ID")
	  REFERENCES "C##KSENIA"."DEPARTMENTS" ("ID") ENABLE;
